name: myexample
on: push 
jobs: 
    myjob1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v6.0.0
        - name: welcome vani 
          run: echo "vani ur welcomed by universe"
        - name: Read files and run script
          run: |
           cat README.md
           chmod +x ex.sh
           ./ex.sh